#pragma once
// Current source-derived Fill/arange templates; not dynamic GPU witnesses.
namespace current_outside {
using namespace native_sequence;
class Binding final:public tiny_full::KernelBinding {
 const J&templates_;J call_;const coupling::ServiceMapper&mapper_;std::vector<std::string>keys_;std::vector<std::vector<tiny_full::SourceNode>>nodes_;std::vector<U>classes_,first_;
 static std::string raw(const J&r){std::string out,h=r.at("raw_bytes_hex");p::need(h.size()==2*p::natural(r.at("size_bytes")),"raw size");for(U i=0;i<h.size();i+=2){auto n=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;throw std::runtime_error("raw hex");};out.push_back(char(n(h[i])*16+n(h[i+1])));}p::need(tiny_sha::sha256(out)==r.at("sha256").get<std::string>(),"raw hash");return out;}
 static U word(const std::string&r){p::need(r.size()<=8,"word width");U x=0;for(U i=0;i<r.size();++i)x|=U(static_cast<unsigned char>(r[i]))<<(8*i);return x;}
public:
 static void admit(const J&c,const J&t){
  p::need(c.at("schema")=="CURRENT_OUTSIDE_FILL_ARANGE_EXECUTION_CALL_V1"&&c.at("process")==J({{"pid",3011726},{"start_ticks",897090720}}),"current outside process");const auto&b=c.at("binding");const auto&a=c.at("raw_argument_record");const auto&l=c.at("launch_before");const auto&r=c.at("launch_return");p::need(b.at("code_sha256")==a.at("code_sha256")&&b.at("function_id")==a.at("function_id"),"current actual static source");
  p::need(a.at("native_launch_binding").at("process")==c.at("process")&&a.at("native_launch_binding").at("native_launch_id")==c.at("native_launch_id")&&b.at("native_launch_id")==c.at("native_launch_id")&&b.at("process")==c.at("process")&&b.at("source_launch_key")==c.at("source_launch_key"),"exact actual binding identity");p::need(tiny_sha::sha256(a.dump())==c.at("raw_argument_sha256").get<std::string>(),"complete raw argument evidence");
  for(auto k:{"grid","block"})p::need(c.at(k)==b.at(k)&&c.at(k)==l.at(k)&&c.at(k)==r.at(k),"same actual geometry");for(auto k:{"code_sha256","parameter_layout_sha256","function_id","stream_u64","context_id"})p::need(l.at(k)==r.at(k)&&l.at(k)==a.at(k),"same current source/layout/context");p::need(!l.contains("cuda_status")&&r.at("cuda_status")==0&&l.at("event_ordinal")<r.at("event_ordinal"),"actual successful callback pair");
  p::need(l.at("static_shared_bytes")==0&&l.at("dynamic_shared_bytes")==0&&c.at("resident_limit_assumption")==1,"no missing shared; explicit conservative resident assumption");for(auto k:{"current_occupancy_observed","compute_transfer_qualified","implicit_register_dependencies_complete","full_simulation_admitted"})p::need(c.at(k)==false,"source-only execution limitations");
  p::need(a.at("arguments").size()==3,"actual3 arguments");auto nr=raw(a.at("arguments")[0]),sr=raw(a.at("arguments")[1]),pr=raw(a.at("arguments")[2]);U n=word(nr),ptr=word(pr);p::need(nr.size()==4&&pr.size()==8&&n==p::natural(b.at("N"))&&ptr==p::natural(c.at("output")),"actual N/output role");
  bool fill=c.at("kind")=="fill";U q=fill?1024:64,size=fill?p::natural(b.at("element_size")):c.at("kind")=="arange_float"?4:8;p::need(fill||c.at("kind")=="arange_float"||c.at("kind")=="arange_long","closed5code family");p::need(c.at("grid")==J::array({(n+q-1)/q,1,1})&&c.at("block")==J::array({fill?128:64,1,1})&&c.at("bytes")==n*size&&c.at("logical_write_bytes")==n*size&&c.at("logical_read_bytes")==0&&p::add(ptr,n*size)==p::natural(c.at("end_exclusive")),"exact source domain/footprint");
  p::need(fill?(sr.size()==size&&b.at("output")==ptr):(b.at("fields").at("output")==ptr&&sr.size()==U(size==4?16:24)),"closed actual argument sizes/route");p::need(t.at("static_codes").contains(b.at("code_sha256").get<std::string>()),"exact current static code");
  p::need(c.at("class_for_cta").size()==p::natural(c.at("grid")[0]),"complete CTA classes");U nodes=0;
  for(U i=0;i<c.at("class_for_cta").size();++i){std::string expected=b.at("code_sha256").get<std::string>()+":"+std::to_string(std::min(q,n-i*q));p::need(c.at("class_for_cta")[i]==expected,"control class bound to raw N/CTA");const auto&cl=t.at("classes").at(expected);p::need(cl.at("quantum")==q&&cl.at("element_size")==size&&cl.at("warps")==p::natural(c.at("block")[0])/32&&cl.at("source_derived_control")==true&&cl.at("dynamic_instruction_path_observed")==false,"sealed derived full source template");nodes=p::add(nodes,cl.at("nodes").size());}p::need(c.at("nodes")==nodes,"entire declared source instruction work");
 }
 Binding(const J&t,const J&c,const coupling::ServiceMapper&mapper):templates_(t),call_(c),mapper_(mapper){admit(c,t);std::map<std::string,U>ids;U offset=0;
  for(const auto&k:c.at("class_for_cta")){std::string key=k;auto it=ids.find(key);if(it==ids.end()){U id=keys_.size();keys_.push_back(key);ids.emplace(key,id);std::vector<tiny_full::SourceNode>ns;for(const auto&n:t.at("classes").at(key).at("nodes")){tiny_full::SourceNode s;s.id=p::natural(n.at("id"));s.warp=p::natural(n.at("warp"));s.ordinal=p::natural(n.at("ordinal"));s.source_ordinal=p::natural(n.at("source_ordinal"));s.pc=p::natural(n.at("pc"));s.mask=p::natural(n.at("effective_mask"));s.compute_elements=p::natural(n.at("elements"));s.pipeline=n.at("pipeline");s.write=n.at("kind")=="global";s.kind=s.write?tiny_full::Kind::Global:n.at("kind")=="control"?tiny_full::Kind::Control:tiny_full::Kind::Compute;s.completion_dependencies=n.at("completion_dependencies").get<std::vector<unsigned>>();s.issue_dependencies=n.at("issue_dependencies").get<std::vector<unsigned>>();p::need(s.id==ns.size(),"dense template nodes");for(auto d:s.completion_dependencies)p::need(d<s.id,"backward complete dependency");for(auto d:s.issue_dependencies)p::need(d<s.id,"backward issue dependency");ns.push_back(std::move(s));}nodes_.push_back(std::move(ns));it=ids.find(key);}first_.push_back(offset);classes_.push_back(it->second);offset=p::add(offset,nodes_[it->second].size());}
 }
 U ctas()const override{return classes_.size();}unsigned warps(U c)const override{p::need(c<ctas(),"CTA domain");return p::natural(call_.at("block")[0])/32;}unsigned resident_limit()const override{return 1;}U first_node(U c)const override{return first_.at(c);}U template_class(U c)const override{return classes_.at(c);}std::span<const tiny_full::SourceNode>nodes(U c)const override{return nodes_.at(classes_.at(c));}
 tiny_full::MemoryDescriptor memory(U c,unsigned member)const override{
  const auto&cl=templates_.at("classes").at(keys_.at(classes_.at(c)));const auto&n=cl.at("nodes").at(member);p::need(n.at("kind")=="global"&&nodes(c)[member].write,"source store only");tiny_full::MemoryDescriptor d;d.path=tiny_full::Path::DirectGlobal;d.write=true;g::ExplicitMemorySubop sub;std::unordered_set<U>seen;U base=p::add(p::natural(call_.at("output")),c*p::natural(cl.at("quantum"))*p::natural(cl.at("element_size"))),mask=0,width=p::natural(n.at("width"));
  for(const auto&x:n.at("address_offsets")){U lane=p::natural(x[0]),address=p::add(base,p::natural(x[1]));p::need(lane<32&&!(mask&(U(1)<<lane))&&p::add(address,width)<=p::natural(call_.at("end_exclusive")),"complete actual source lane width");mask|=U(1)<<lane;sub.ranges.push_back({int(lane),address,width});sub.source_member_ordinals.push_back(int(lane));sub.requested_bytes+=width;for(U line=address/128*128,last=(address+width-1)/128*128;;line+=128){g::CacheLineKey key{1,line};(void)mapper_.map(key);if(seen.insert(line).second)d.lines.push_back(key);if(line==last)break;}}
  p::need(mask==p::natural(n.at("effective_mask"))&&mask>0,"source control store mask");d.global_bytes=sub.requested_bytes;d.global_subops.push_back(std::move(sub));return d;
 }
 J evidence()const override{return {{"schema","CURRENT_SOURCE_DERIVED_OUTSIDE_TINY_V1"},{"current_call",call_},{"current_source_control_derived",true},{"complete_explicit_instruction_and_register_DAG",true},{"source_dynamic_instruction_path_observed",false},{"resident_limit_assumption",1},{"constant_cache_timing_modeled",false},{"implicit_register_dependencies_complete",false},{"current_occupancy_observed",false},{"compute_transfer_qualified",false},{"full_simulation_admitted",false}};}
};
}
