#pragma once
#include "mixed_seals.h"
namespace canonical_mixed643 {
using namespace native_sequence;
J object_views(const J&c){if(c.at("schema")=="CANONICAL_INDEXPUT_ESTIMATED_TARGET_V1"||c.at("schema")=="CANONICAL_PREFILLCOPY_ESTIMATED_TARGET_V1"){J out=J::object();const std::vector<std::string> roles=c.at("schema")=="CANONICAL_INDEXPUT_ESTIMATED_TARGET_V1"?std::vector<std::string>{"indices","value_input","destination"}:std::vector<std::string>{"value_input","destination"};for(const auto&role:roles){const auto&o=c.at(role);U lo=p::natural(o.at("data_address")),bytes=p::natural(o.at("addressed_span_bytes"));out[role]={{"pointer",lo},{"bytes",bytes},{"end_exclusive",p::add(lo,bytes)},{"logical_identity",o.at("logical_identity")},{"root",{{"id",o.at("logical_root")}}}};}return out;}return c.at("objects");}
J union_map(const std::vector<const J*>&calls){std::vector<std::pair<U,U>>spans;for(auto*c:calls)for(const auto&o:object_views(*c)){U lo=p::natural(o.at("pointer")),hi=p::natural(o.at("end_exclusive"));p::need(hi<=UINT64_MAX-127,"map bound");spans.emplace_back(lo/128*128,(hi+127)/128*128);}std::sort(spans.begin(),spans.end());std::vector<std::pair<U,U>>merged;for(auto x:spans){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(x.second,merged.back().second);else merged.push_back(x);}J rows=J::array();U off=0;for(auto[lo,hi]:merged){rows.push_back({{"source_base",lo},{"bytes",hi-lo},{"service_base",off}});off=p::add(off,hi-lo);}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}
struct Target{std::string family;const J*call;};
struct Model{
 std::unique_ptr<canonical_silu::Model>silu;std::unique_ptr<canonical_fused::Model>fused;std::unique_ptr<canonical_rotary::Model>rotary;std::unique_ptr<canonical_norm::Model>norm;std::unique_ptr<canonical_indexput::Model>indexput;std::unique_ptr<canonical_prefillcopy::Model>copy;std::unique_ptr<P28Catalog>p28;J p28_plan;std::vector<Target>calls;J workflow;
 Model(const J&in){keys(in,{"schema","workflow_file","memory_model","service_address_map","selected_source_keys","max_kernel_cycles","aggregate_observations","p28_template"});p::need(in.at("schema")=="CANONICAL_MIXED643_MODELED_SEQUENCE_V1"&&in.at("aggregate_observations").is_boolean(),"mixed643 explicit input");p::need(in.at("workflow_file")==mixed_seals().at("workflow_file"),"canonical workflow seal");workflow=strict_parse(check_pin(in.at("workflow_file")));p::need(workflow.at("call_count")==1138&&workflow.at("process")==J({{"pid",1925216},{"start_ticks",857625100}}),"same canonical process");
  std::map<std::string,J>seals={{"SiLU",canonical_silu::seals()},{"FusedNorm",canonical_fused::seals()},{"Rotary",canonical_rotary::seals()},{"PlainNorm",canonical_norm::seals()},{"IndexPut",canonical_indexput::seals()},{"PrefillCopy",canonical_prefillcopy::seals()}};std::map<std::string,J>plans;std::map<std::string,std::pair<std::string,const J*>>available;
  for(const auto&[family,s]:seals){p::need(s.at("memory_model")==in.at("memory_model"),"one unchanged profile");plans.emplace(family,strict_parse(check_pin(s.at("plan_file"))));for(const auto&t:plans.at(family).at("calls"))p::need(available.emplace(t.at("source_launch_key").get<std::string>(),std::make_pair(family,&t)).second,"unique union target");}p28_plan=strict_parse(check_pin(mixed_seals().at("p28_plan")));p::need(p28_plan.at("call_count")==32&&p28_plan.at("target_process")==workflow.at("process"),"P28 closed canonical domain");for(const auto&t:p28_plan.at("calls"))p::need(available.emplace(t.at("source_launch_key").get<std::string>(),std::make_pair("P28QKV",&t)).second,"unique P28 target");p::need(available.size()==643,"closed643 union");
  const auto&chosen=in.at("selected_source_keys");p::need(chosen.is_array()&&!chosen.empty()&&chosen.size()<=643,"bounded selected union");std::set<std::string>wanted;for(const auto&k:chosen)p::need(k.is_string()&&wanted.insert(k.get<std::string>()).second&&available.count(k.get<std::string>()),"unique supported target");std::map<std::string,J>keys_by;std::map<std::string,std::vector<const J*>>targets_by;std::vector<const J*>all;std::vector<std::pair<std::string,std::string>>order;
  for(const auto&w:workflow.at("calls")){auto key=w.at("source_launch_key").get<std::string>();if(!wanted.count(key))continue;p::need(chosen.at(order.size())==key,"canonical actual order");p::need(w.at("stream_u64")==0&&w.at("context_id")==1,"closed selected canonical stream/context");auto[family,t]=available.at(key);for(auto f:{"native_launch_binding","code_sha256","phase","module_scope","function_id","context_id","stream_u64","argument_line_sha256","native_before_sha256","native_return_sha256","grid","block","native_resources"})if(family!="P28QKV"||std::string(f)!="stream_u64")p::need(t->at(f)==w.at(f),"exact canonical target field");p::need(t->at("process")==workflow.at("process"),"samePID");if(!keys_by.count(family))keys_by[family]=J::array();keys_by[family].push_back(key);targets_by[family].push_back(t);all.push_back(t);order.emplace_back(family,key);}
  p::need(order.size()==chosen.size()&&in.at("service_address_map")==union_map(all),"one global service map");auto env=[&](const std::string&f,const char*schema){return J{{"schema",schema},{"plan_file",seals.at(f).at("plan_file")},{"memory_model",in.at("memory_model")},{"service_address_map",union_map(targets_by.at(f))},{"selected_source_keys",keys_by.at(f)},{"max_kernel_cycles",in.at("max_kernel_cycles")},{"aggregate_observations",in.at("aggregate_observations")}};};
  if(keys_by.count("SiLU"))silu=std::make_unique<canonical_silu::Model>(env("SiLU","CANONICAL_SILU_MODELED_SEQUENCE_V1"));if(keys_by.count("FusedNorm"))fused=std::make_unique<canonical_fused::Model>(env("FusedNorm","CANONICAL_FUSED_NORM_MODELED_SEQUENCE_V1"));if(keys_by.count("Rotary"))rotary=std::make_unique<canonical_rotary::Model>(env("Rotary","CANONICAL_ROTARY_MODELED_SEQUENCE_V1"));if(keys_by.count("PlainNorm"))norm=std::make_unique<canonical_norm::Model>(env("PlainNorm","CANONICAL_NORM_MODELED_SEQUENCE_V1"));if(keys_by.count("IndexPut"))indexput=std::make_unique<canonical_indexput::Model>(env("IndexPut","CANONICAL_INDEXPUT_MODELED_SEQUENCE_V1"));if(keys_by.count("PrefillCopy"))copy=std::make_unique<canonical_prefillcopy::Model>(env("PrefillCopy","CANONICAL_PREFILLCOPY_MODELED_SEQUENCE_V1"));
  if(keys_by.count("P28QKV"))p28=std::make_unique<P28Catalog>(in.at("p28_template"),mixed_seals().at("p28_template"));
  std::map<std::string,const J*>live;auto add=[&](const auto&m){if(m)for(auto*t:m->calls)p::need(live.emplace(t->at("source_launch_key").template get<std::string>(),t).second,"stable target ownership");};add(silu);add(fused);add(rotary);add(norm);add(indexput);add(copy);if(p28)for(const auto&t:p28_plan.at("calls"))if(wanted.count(t.at("source_launch_key").get<std::string>()))p::need(live.emplace(t.at("source_launch_key").get<std::string>(),&t).second,"stable P28 call ownership");for(auto[f,k]:order)calls.push_back({f,live.at(k)});auto pool=receipt();p::need(p::natural(pool.at("encoded_source_bytes"))<=64U<<20&&p::natural(pool.at("register_template_nodes"))<=131072&&p::natural(pool.at("typed_register_dependency_edges"))<=524288&&p::natural(pool.at("memory_records"))<=32768&&p::natural(pool.at("memory_lane_tuples"))<=1048576,"unchanged pooled budgets");
 }
 const SourceBundle&source(const Target&t)const{p::need(t.family!="Rotary"&&t.family!="IndexPut"&&t.family!="PrefillCopy"&&t.family!="P28QKV","family source has distinct type");return t.family=="SiLU"?silu->source():t.family=="FusedNorm"?fused->source(*t.call):norm->source(*t.call);}
 void finish(){if(silu)silu->catalog->seals.finish();if(fused)fused->catalog->seals.finish();if(rotary)rotary->catalog->seals.finish();if(norm)norm->catalog->seals.finish();if(indexput)indexput->catalog->seals.finish();if(copy)copy->catalog->seals.finish();(void)check_pin(mixed_seals().at("workflow_file"));(void)check_pin(mixed_seals().at("p28_plan"));}
 J receipt()const{J out={{"schema","MIXED643_IMMUTABLE_SOURCE_POOL_V1"},{"source_bytes_are_RSS",false},{"target_model_calls",calls.size()},{"original_source_addresses_used_for_execution",false},{"family_pools",J::object()}};for(auto k:{"sources","encoded_source_bytes","register_template_nodes","typed_register_dependency_edges","memory_records","memory_lane_tuples","oracle_validations"})out[k]=0;auto add=[&](const char*name,const J&r,bool cls){out["family_pools"][name]=r;for(auto k:{"sources","encoded_source_bytes","memory_records","memory_lane_tuples","oracle_validations"})out[k]=out.at(k).get<U>()+r.at(k).get<U>();out["register_template_nodes"]=out.at("register_template_nodes").get<U>()+r.at(cls?"unique_template_nodes":"register_template_nodes").get<U>();out["typed_register_dependency_edges"]=out.at("typed_register_dependency_edges").get<U>()+r.at(cls?"unique_typed_edges":"typed_register_dependency_edges").get<U>();};if(silu)add("SiLU",silu->catalog->receipt(),false);if(fused)add("FusedNorm",fused->catalog->receipt(),false);if(rotary)add("Rotary",rotary->catalog->receipt(),true);if(norm)add("PlainNorm",norm->catalog->receipt(),false);if(indexput)add("IndexPut",canonical_mixed611::index_pool_receipt(*indexput->catalog),false);if(copy)add("PrefillCopy",canonical_mixed611::copy_pool_receipt(*copy->catalog),false);if(p28)add("P28QKV",p28->receipt(),false);return out;}
};
}
