#pragma once
namespace helper_bridge {
using namespace prefill_gemm;
struct Range {int lane;U address,width;};
struct Node {int old,warp,ordinal,pc,elements;U effective,width,memory_ordinal=0;bool has_secondary_exit=false,has_secondary_branch=false;U secondary_exit_mask=0,secondary_branch_successor=0;std::string kind,pipe,opcode,memop;std::vector<int>deps,issues;std::vector<Range>global,shared;};
struct ControlClass {
 std::string key,family;int warps,resident;U ranges=0,read=0,write=0,edges=0;std::vector<Node>nodes;std::vector<g::CtaGraphStore::Span>spans;J call,metadata;
 ControlClass(const J&t):key(t.at("key")),family(t.at("family")),call(t.at("call")){
  need(t.at("native_target_qualified")==false&&t.at("implicit_register_dependencies_complete")==false,"helper estimate authority");warps=int(integer(t.at("warps"),32));U threads=integer(t.at("resources").at("threads_per_cta"),1024);need(threads>0&&warps==int((threads+31)/32),"actual helper ceil warp geometry");need(t.at("perwarp").size()==U(warps)&&t.at("memory_counts").size()==U(warps),"exact helper warp census size");resident=int(integer(t.at("resources").at("max_active_blocks_per_sm"),32));need(resident>0,"actual helper resource cap");U extent=add(integer(t.at("resources").at("static_shared_bytes")),integer(t.at("resources").at("dynamic_shared_bytes")));const auto&ns=t.at("nodes");need(ns.size()==integer(t.at("node_count"),100000)&&tiny_sha::sha256(ns.dump())==t.at("node_sha256").get<std::string>(),"helper node count/SHA");std::vector<int>last(warps,-1);std::vector<U>base(warps);for(int w=1;w<warps;++w)base[w]=base[w-1]+integer(t.at("perwarp")[w-1]);std::set<int>oldids;std::vector<U>memnext(warps);U comp=0,issue=0;
  for(U i=0;i<ns.size();++i){const auto&v=ns[i];Node n;n.old=int(integer(v.at("original_id"),ns.size()-1));n.warp=int(integer(v.at("warp"),warps-1));n.ordinal=int(integer(v.at("program_ordinal"),integer(t.at("perwarp")[n.warp])-1));n.pc=int(integer(v.at("pc")));n.effective=integer(v.at("effective_mask"),UINT32_MAX);
   n.has_secondary_exit=v.contains("observed_secondary_predicate_exit_mask");n.has_secondary_branch=v.contains("observed_secondary_predicate_branch_successor");
   need(v.contains("EXIT_secondary_predicate_value")==n.has_secondary_exit,"secondary EXIT metadata paired");
   if(n.has_secondary_exit){need(v.at("opcode")=="EXIT"&&v.at("kind")=="control"&&v.at("EXIT_secondary_predicate_value").is_null(),"observed EXIT value remains unknown");n.secondary_exit_mask=integer(v.at("observed_secondary_predicate_exit_mask"),UINT32_MAX);need((n.secondary_exit_mask&~n.effective)==0,"observed EXIT subset of original effective mask");}
   if(n.has_secondary_branch){need(v.at("opcode")=="BRA"&&v.at("kind")=="control","observed branch successor belongs to BRA control");n.secondary_branch_successor=integer(v.at("observed_secondary_predicate_branch_successor"),UINT32_MAX);}
   // Preserve the complete already-lowered graph. No EXIT mask is used to prune nodes.
U active=integer(v.at("active_mask"),UINT32_MAX),valid=(1ULL<<std::min(U(32),threads-32*n.warp))-1;need((n.effective&~active)==0&&(active&~valid)==0,"actual native active/effective lane domain");n.width=integer(v.at("width"),16);n.elements=int(integer(v.at("elements"),32));n.kind=v.at("kind");n.pipe=v.at("pipeline").is_null()?"":v.at("pipeline").get<std::string>();n.opcode=v.at("opcode");n.memop=v.at("memory_op").is_null()?"":v.at("memory_op").get<std::string>();need(n.elements>0&&n.old==int(base[n.warp])+n.ordinal&&oldids.insert(n.old).second&&n.ordinal==last[n.warp]+1,"complete original helper warp instruction stream");last[n.warp]=n.ordinal;std::set<int>seen;
   for(auto x:v.at("depends_on")){int d=int(integer(x,ns.size()-1));need(d<int(i)&&seen.insert(d).second,"helper forward completion edge");n.deps.push_back(d);++comp;}for(auto x:v.at("issue_depends_on")){int d=int(integer(x,ns.size()-1));need(d<int(i)&&seen.insert(d).second,"helper forward disjoint issue edge");n.issues.push_back(d);++issue;}
   for(bool shared:{false,true}){const auto&rs=v.at(shared?"shared_ranges":"global_ranges");U mask=0;for(const auto&x:rs){need(x.size()==3,"actual helper lane/address/width");Range r{int(integer(x[0],31)),integer(x[1]),integer(x[2],16)};need((r.width==1||r.width==2||r.width==4||r.width==8||r.width==16)&&r.width==n.width&&!(mask&(1ULL<<r.lane))&&r.address<=UINT64_MAX-r.width,"unique bounded helper request");mask|=1ULL<<r.lane;if(shared){need(r.address+r.width<=extent,"observed shared extent");n.shared.push_back(r);}else{bool found=false;for(const auto&q:t.at("service_ranges"))found|=integer(q[0])<=r.address&&r.address+r.width<=integer(q[1]);need(found,"same call request inside declared window");n.global.push_back(r);if(n.memop=="R")read+=r.width;else write+=r.width;}++ranges;}if(!rs.empty())need(mask==n.effective,"all effective memory lanes retained");}
   if(n.kind=="global"){n.memory_ordinal=integer(v.at("memory_record_ordinal"));need(!n.global.empty()&&n.shared.empty()&&(n.memop=="R"||n.memop=="W")&&integer(v.at("memory_record_ordinal"))==memnext[n.warp]++,"actual global encounter ordinal");}
   else if(n.kind=="shared")need(n.global.empty()&&!n.shared.empty()&&(n.memop=="R"||n.memop=="W"),"ordinary observed shared operation");
   else{need(n.global.empty()&&n.shared.empty()&&(n.kind=="compute"||n.kind=="control"||n.kind=="barrier"),"closed helper compute/control/barrier");if(n.kind!="barrier")need(n.pipe=="SIMD"||n.pipe=="SFU"||n.pipe=="SHFL","existing helper compute service");}
   nodes.push_back(std::move(n));
  }
  for(int w=0;w<warps;++w)need(last[w]+1==int(integer(t.at("perwarp")[w]))&&memnext[w]==integer(t.at("memory_counts")[w]),"helper warp/global census");need(read==integer(t.at("requested_read_bytes"))&&write==integer(t.at("requested_write_bytes"))&&ranges==integer(t.at("ranges"))&&comp==integer(t.at("completion_edges"))&&issue==integer(t.at("issue_edges")),"helper typed edge/traffic census");edges=comp+issue;spans.push_back({0,int(nodes.size())});metadata=t;metadata.erase("nodes");J observed=J::array();for(const auto&n:nodes)if(n.has_secondary_exit||n.has_secondary_branch){J row={{"original_id",n.old},{"warp",n.warp},{"ordinal",n.ordinal},{"pc",n.pc}};if(n.has_secondary_exit){row["observed_secondary_predicate_exit_mask"]=n.secondary_exit_mask;row["EXIT_secondary_predicate_value"]=nullptr;}if(n.has_secondary_branch)row["observed_secondary_predicate_branch_successor"]=n.secondary_branch_successor;observed.push_back(std::move(row));}metadata["secondary_control_nodes"]=observed.size();metadata["secondary_control_metadata_sha256"]=tiny_sha::sha256(observed.dump());
 }
};
}
