#pragma once
namespace canonical_mixed643 {
struct ModeledPrepared {
 const SourceBundle* bundle=nullptr;const canonical_indexput::SourceBundle* index_bundle=nullptr;const canonical_prefillcopy::SourceBundle* copy_bundle=nullptr;const native_cta_sequence::SourceBundle* class_bundle=nullptr;const p::Program*program=nullptr;const J&call;std::string family;U executed,total_nodes,expected_read,expected_write;int resident;g::CtaGraphStore::Limits limits;J budget;
 ModeledPrepared(const Model&m,const Target&t,bool eager):call(*t.call),family(t.family){
  limits.max_live_nodes=5000000;
  if(family=="P28QKV"){p::need(!eager,"P28 full48 eager is outside bounded reference domain");executed=48;resident=1;total_nodes=39404*48;expected_read=1310720*48;expected_write=8192*48;limits.max_nodes_per_cta=39404;limits.max_explicit_ranges_per_cta=374528;limits.max_live_nodes=2000000;limits.max_live_explicit_ranges=24000000;budget={{"nodes_per_cta",39404},{"stored_ranges_per_cta",374528},{"conservative_live_ctas",48},{"conservative_live_nodes",total_nodes},{"conservative_live_ranges",374528*48},{"native_resource_cap",1}};}
  else if(family=="Rotary"){class_bundle=&m.rotary->source(call);program=&class_bundle->program;native_cta_sequence::Prepared old(*class_bundle,J{{"catalog_id",call.at("phase")},{"prefix_ctas",0}},eager);executed=old.executed;resident=old.resident;limits=old.limits;budget=old.budget;auto&cat=class_bundle->catalog;total_nodes=cat.sum(executed,&native_cta_class::Binding::nodes);expected_read=cat.sum(executed,&native_cta_class::Binding::read);expected_write=cat.sum(executed,&native_cta_class::Binding::write);U maximum=0;for(const auto&b:cat.bindings)maximum=std::max(maximum,b.original);U live=p::natural(budget.at("conservative_live_ctas"))*maximum;p::need(maximum<=limits.max_explicit_ranges_per_cta&&live<=limits.max_live_explicit_ranges,"class original lane budget");budget["maximum_stored_ranges_per_cta"]=maximum;budget["conservative_live_ranges"]=live;}
  else if(family=="IndexPut"){index_bundle=&m.indexput->source(call);program=&index_bundle->program;canonical_indexput::ModeledPrepared old(*index_bundle,call,eager);executed=old.executed;resident=old.resident;limits=old.limits;budget=old.budget;total_nodes=p::multiply(executed,index_bundle->registers.nodes.size());expected_read=p::multiply(program->bodies[0].read,executed);expected_write=p::multiply(program->bodies[0].write,executed);}
  else if(family=="PrefillCopy"){copy_bundle=&m.copy->source();program=&copy_bundle->program;canonical_prefillcopy::ModeledPrepared old(*copy_bundle,call,eager);executed=old.executed;resident=old.resident;limits=old.limits;budget=old.budget;total_nodes=p::multiply(executed,copy_bundle->registers.nodes.size());expected_read=p::multiply(program->bodies[0].read,executed);expected_write=p::multiply(program->bodies[0].write,executed);}
  else{bundle=&m.source(t);program=&bundle->program;const auto&reg=bundle->registers;executed=p::natural(call.at("grid")[0],32);resident=bundle->resident;U ranges=p::natural(bundle->budget.at("stored_ranges_per_cta")),frontier=std::min(executed,U(2)*48*resident),nodes=p::multiply(frontier,reg.nodes.size());p::need(nodes<=limits.max_live_nodes&&ranges<=limits.max_explicit_ranges_per_cta&&frontier*ranges<=limits.max_live_explicit_ranges,"bounded residency");total_nodes=p::multiply(executed,reg.nodes.size());if(eager)p::need(total_nodes<=200000,"bounded eager");expected_read=p::multiply(program->bodies[0].read,executed);expected_write=p::multiply(program->bodies[0].write,executed);budget={{"nodes_per_cta",reg.nodes.size()},{"stored_ranges_per_cta",ranges},{"conservative_live_ctas",frontier},{"conservative_live_nodes",nodes},{"conservative_live_ranges",frontier*ranges},{"native_resource_cap",resident},{"live_node_limit",limits.max_live_nodes}};}
 }
};
}
