#pragma once
#include "sealed_inputs.h"
namespace canonical_full {
using namespace native_sequence;
using Target=canonical_mixed643::Target;
const std::set<std::string>GEMMS={"P28QKV","GEMMO","GEMMGate","GEMMDown"};
bool is_gemm(const std::string&f){return GEMMS.count(f)!=0;}

const std::set<std::string> ATTENTIONS={"AttentionPrefill","AttentionDecode1","AttentionDecode2"};
bool is_attention(const std::string&f){return ATTENTIONS.count(f)!=0;}
bool is_framed(const std::string&f){return is_gemm(f)||is_attention(f);}
bool is_helper(const std::string&f){return f.rfind("Helper",0)==0;}
J object_views(const J&c){if(!c.contains("service_ranges"))return canonical_mixed643::object_views(c);if(c.contains("helper_objects")&&!c.at("helper_objects").empty())return c.at("helper_objects");J o=J::object();if(c.contains("role_windows"))for(const auto&i:c.at("role_windows").items()){const auto&v=i.value();o[i.key()]={{"logical_identity",v.value("logical_identity",J(nullptr))},{"pointer",v.value("argument_pointer",v.value("pointer",J(nullptr)))},{"bytes",nullptr},{"minimum_service_windows",v.value("service_byte_intervals",J::array())},{"actual_extent_known",false}};}return o;}
J union_map(const std::vector<const J*>&cs){std::vector<std::pair<U,U>>ss;for(auto*c:cs){if(c->contains("service_ranges")){for(const auto&q:c->at("service_ranges")){U lo=p::natural(q[0]),hi=p::natural(q[1]);p::need(lo&&lo<hi&&lo%128==0&&hi%128==0,"exact minimum line window");ss.emplace_back(lo,hi);}}else{J v=object_views(*c);for(const auto&i:v.items()){const auto&o=i.value();U lo=p::natural(o.at("pointer")),hi=p::natural(o.at("end_exclusive"));p::need(lo<hi&&hi<=UINT64_MAX-127,"bounded legacy object view");ss.emplace_back(lo/128*128,(hi+127)/128*128);}}}std::sort(ss.begin(),ss.end());std::vector<std::pair<U,U>>merged;for(auto x:ss){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(merged.back().second,x.second);else merged.push_back(x);}J rows=J::array();U off=0;for(auto x:merged){rows.push_back({{"source_base",x.first},{"bytes",x.second-x.first},{"service_base",off}});off+=x.second-x.first;}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}

struct Model {
 std::unique_ptr<canonical_mixed643::Model>legacy;std::unique_ptr<canonical_gemv::Model>gemv;std::unique_ptr<helper_bridge::Catalog>helpers;std::map<std::string,J>plans;std::map<std::string,Target>available;std::vector<Target>calls;J workflow,added;U prefix=0;
 explicit Model(const J&in,const std::string&helperraw){const J fixed=seals();keys(in,{"schema","workflow_file","memory_model","service_address_map","selected_source_keys","prefix_ctas_per_call","max_kernel_cycles","aggregate_observations","frames"});p::need(in.at("schema")=="CANONICAL_FULL_RUNTIME_COMPRESSED_V4"&&in.at("workflow_file")==seals().at("workflow_file"),"fixed complete workflow");p::need(in.at("aggregate_observations").is_boolean(),"boolean observer flag");prefix=p::natural(in.at("prefix_ctas_per_call"),512);workflow=strict_parse(check_pin(seals().at("workflow_file")));p::need(workflow.at("call_count")==1138,"whole canonical registry");
  for(const auto&i:fixed.at("plans").items())plans.emplace(i.key(),strict_parse(check_pin(i.value())));
  auto all=[&](const std::vector<std::string>&fs){std::set<std::string>want;std::vector<const J*>cs;for(const auto&f:fs)for(const auto&c:plans.at(f).at("calls")){want.insert(c.at("source_launch_key"));cs.push_back(&c);}J ks=J::array();for(const auto&w:workflow.at("calls"))if(want.count(w.at("source_launch_key")))ks.push_back(w.at("source_launch_key"));return std::make_pair(ks,union_map(cs));};
  auto six=all({"SiLU","FusedNorm","Rotary","PlainNorm","IndexPut","PrefillCopy"});p::need(six.first.size()==611,"all old six-family sources loaded once");J old=in;old.erase("frames");old.erase("prefix_ctas_per_call");old["schema"]="CANONICAL_MIXED643_MODELED_SEQUENCE_V1";old["selected_source_keys"]=six.first;old["service_address_map"]=six.second;old["p28_template"]=nullptr;legacy=std::make_unique<canonical_mixed643::Model>(old);
  std::cerr<<"FULL_RUNTIME_STAGE GEMV"<<std::endl;auto vs=all({"GEMV"});J ve={{"schema","CANONICAL_GEMV_MODELED_SEQUENCE_V1"},{"plan_file",canonical_gemv::seals().at("plan_file")},{"memory_model",in.at("memory_model")},{"service_address_map",vs.second},{"selected_source_keys",vs.first},{"prefix_ctas",0},{"max_kernel_cycles",in.at("max_kernel_cycles")},{"aggregate_observations",in.at("aggregate_observations")}};gemv=std::make_unique<canonical_gemv::Model>(ve);
  for(const auto&t:legacy->calls)p::need(available.emplace(t.call->at("source_launch_key").get<std::string>(),t).second,"unique legacy route");for(const auto*c:gemv->calls)p::need(available.emplace(c->at("source_launch_key").get<std::string>(),Target{"GEMV",c}).second,"unique GEMV route");for(const auto&f:GEMMS)for(const auto&c:plans.at(f).at("calls"))p::need(available.emplace(c.at("source_launch_key").get<std::string>(),Target{f,&c}).second,"unique GEMM route");p::need(available.size()==998,"old998 exact");added=strict_parse(check_pin(fixed.at("added_calls")));for(const auto&c:added.at("calls"))p::need(available.emplace(c.at("source_launch_key").get<std::string>(),Target{c.at("runtime_family"),&c}).second,"unique new exact target");p::need(available.size()==p::natural(fixed.at("registered_call_count")),"all registered exact targets");
  std::cerr<<"FULL_RUNTIME_STAGE helpers"<<std::endl;helpers=std::make_unique<helper_bridge::Catalog>(helperraw,fixed.at("helpers"));for(const auto&i:helpers->models){p::need(available.count(i.first)&&is_helper(available.at(i.first).family),"helper exact target registered");const auto&call=*available.at(i.first).call;const auto&h=*i.second;for(auto k:{"source_launch_key","process","grid","block","native_resources","code_sha256","argument_line_sha256"})p::need(h.call.at(k)==call.at(k),"same current-process helper call");p::need(h.metadata.at("service_ranges")==call.at("service_ranges"),"same complete helper service windows");}std::cerr<<"FULL_RUNTIME_STAGE added-workflow-binding"<<std::endl;const auto&ks=in.at("selected_source_keys");p::need(ks.is_array()&&!ks.empty()&&ks.size()<=available.size(),"selected bounded registered calls");std::set<std::string>wanted;for(const auto&k:ks)p::need(k.is_string()&&wanted.insert(k.get<std::string>()).second&&available.count(k.get<std::string>()),"duplicate or unsupported helper/foreign target");std::vector<const J*>selected;U bound=0;
  for(const auto&w:workflow.at("calls")){auto key=w.at("source_launch_key").get<std::string>();if(!available.count(key))continue;try{const auto&t=available.at(key);const J&c=*t.call;p::need(w.at("stream_u64").is_number_integer()&&!w.at("stream_u64").is_boolean()&&w.at("stream_u64")==0&&w.at("context_id")==1,"canonical stream0/context1");for(auto k:{"native_launch_binding","code_sha256","phase","module_scope","function_id","context_id","argument_line_sha256","native_before_sha256","native_return_sha256","grid","block","native_resources"})p::need(c.at(k)==w.at(k),"same-process canonical bound field");p::need(c.at("process")==workflow.at("process"),"same current target PID");if(t.family!="P28QKV")p::need(c.at("stream_u64")==w.at("stream_u64"),"plan stream binding");++bound;if(!wanted.count(key))continue;p::need(ks.at(calls.size())==key,"original actual call order");calls.push_back(t);selected.push_back(t.call);}catch(const std::exception&e){throw std::runtime_error("Workflow binding "+key+": "+e.what());}}
  std::cerr<<"FULL_RUNTIME_STAGE union-map"<<std::endl;p::need(bound==available.size()&&calls.size()==wanted.size()&&in.at("service_address_map")==union_map([&]{std::vector<const J*> whole;for(const auto& w:workflow.at("calls"))whole.push_back(available.at(w.at("source_launch_key").get<std::string>()).call);return whole;}()),"complete route and one fixed selected full-object union map");
 }
 void finish(){(void)check_pin(seals().at("added_calls"));legacy->finish();gemv->catalog->seals.finish();const J fixed=seals();for(const auto&i:fixed.at("plans").items())(void)check_pin(i.value());(void)check_pin(seals().at("workflow_file"));}
 J receipt()const{return {{"registered_source_census",seals().at("registered_pool")},{"legacy_six",legacy->receipt()},{"GEMV",gemv->catalog->receipt()},{"loaded_legacy_and_GEMV_models",7},{"SourceBundle_DOM_copies_per_source",1},{"encoded_source_bytes_are_RSS",false},{"original_source_addresses_used_for_execution",false}};}
};
struct GemmCatalog {
 std::unique_ptr<p28::Model>p28model;std::unique_ptr<prefill_gemm::Model>nextmodel;std::unique_ptr<attention_bridge::Model>attentionmodel;std::string family,key;U nodes=0,edges=0,ranges=0,read=0,write=0;int warps=4;
 GemmCatalog(const Target&t,U count,const std::string&raw):family(t.family),key(t.call->at("source_launch_key")){
  J j=frame_bridge::parse(raw);auto s=seals().at("frame_nodes").at(family);auto ns=j.at("nodes").dump();p::need(ns.size()==p::natural(s.at("bytes"))&&tiny_sha::sha256(ns)==s.at("sha256").get<std::string>(),"sealed exact RAM CTA nodes");const J&c=*t.call;if(is_attention(family)){j["selected_source_key"]=key;j["role_windows"]=c.at("role_windows");j["ctas"]=count;attentionmodel=std::make_unique<attention_bridge::Model>(j);nodes=attentionmodel->nodes.size();ranges=attentionmodel->ranges;read=attentionmodel->read;write=attentionmodel->write;for(const auto&n:attentionmodel->nodes)edges+=n.deps.size()+n.issues.size();p::need(nodes==p::natural(s.at("nodes"))&&edges==p::natural(s.at("edges")),"Attention template census");return;}const auto roles=std::array<std::string,3>{"weight","input","output"};std::array<U,3>strides;
  if(family=="P28QKV"){strides={1048576,0,256};p::need(c.at("role")=="self_attn.qkv_proj"&&c.at("grid")==J::array({48,1,1}),"QKV role domain");}
  else {const std::string role=family=="GEMMO"?"o":family=="GEMMGate"?"gate":"down";p::need(j.at("role")==role,"role frame identity");auto prof=prefill_gemm::profile(role);strides=prof.strides;p::need(c.at("grid")==J::array({prof.grid,1,1})&&c.at("native_resources").at("static_shared_bytes")==49152&&c.at("native_resources").at("dynamic_shared_bytes")==prof.shared-49152&&c.at("native_resources").at("registers")==prof.regs,"new role resource domain");}
  J objects=J::array();for(int i=0;i<3;++i){const auto&o=c.at("objects").at(roles[i]);objects.push_back({{"role",roles[i]},{"logical_identity",o.at("logical_identity")},{"pointer",o.at("pointer")},{"bytes",o.at("bytes")},{"cta_stride",strides[i]}});}j["objects"]=objects;j["ctas"]=count;
  if(family=="P28QKV"){p28model=std::make_unique<p28::Model>(j);nodes=p28model->nodes.size();ranges=p28model->ranges;read=p28model->read;write=p28model->write;for(const auto&n:p28model->nodes)edges+=n.deps.size()+n.issues.size();}
  else{nextmodel=std::make_unique<prefill_gemm::Model>(j);nodes=nextmodel->nodes.size();ranges=nextmodel->ranges;read=nextmodel->read;write=nextmodel->write;for(const auto&n:nextmodel->nodes)edges+=n.deps.size()+n.issues.size();}
  p::need(nodes==p::natural(s.at("nodes"))&&edges==p::natural(s.at("edges")),"actual RAM template nodes/typed edges census");
 }
};
struct NextBuilder:prefill_gemm::Builder {bool fast_hash=false,merge_ranges=false;int kernel_index=0;const std::vector<g::CtaGraphStore::Span>&spans;U&built_nodes;U&retired_nodes;std::vector<std::string>&retired_semantics;std::vector<std::string>retired_kernel_semantics;explicit NextBuilder(const prefill_gemm::Model&m):prefill_gemm::Builder(m),spans(m.spans),built_nodes(built),retired_nodes(retired),retired_semantics(digests),retired_kernel_semantics(m.ctas){}void retire(int c,const std::vector<g::DAGNode*>&ns,g::Cycle cy){prefill_gemm::Builder::retire(c,ns,cy);tiny_sha::Sha256 h;h.add("kernel="+std::to_string(kernel_index)+":"+digests[c]+"\n");retired_kernel_semantics[c]=h.hex();}};
struct AttentionBuilder:attention_bridge::Builder {bool fast_hash=false,merge_ranges=false;int kernel_index=0;const std::vector<g::CtaGraphStore::Span>&spans;U&built_nodes;U&retired_nodes;std::vector<std::string>&retired_semantics;std::vector<std::string>retired_kernel_semantics;explicit AttentionBuilder(const attention_bridge::Model&m):attention_bridge::Builder(m),spans(m.spans),built_nodes(built),retired_nodes(retired),retired_semantics(digests),retired_kernel_semantics(m.ctas){}void retire(int c,const std::vector<g::DAGNode*>&ns,g::Cycle cy){attention_bridge::Builder::retire(c,ns,cy);tiny_sha::Sha256 h;h.add("kernel="+std::to_string(kernel_index)+":"+digests[c]+"\n");retired_kernel_semantics[c]=h.hex();}};
struct Prepared {
 const Target&t;const J&call;std::string family;const SourceBundle*bundle=nullptr;const canonical_indexput::SourceBundle*index_bundle=nullptr;const canonical_prefillcopy::SourceBundle*copy_bundle=nullptr;const native_cta_sequence::SourceBundle*class_bundle=nullptr;const p::Program*program=nullptr;U executed=0,total_nodes=0,expected_read=0,expected_write=0;int resident=0,warps=0;g::CtaGraphStore::Limits limits;J budget;
 Prepared(const Model&m,const Target&target,bool eager):t(target),call(*target.call),family(target.family){const auto&f=t.family;const auto&c=*t.call;
  if(is_helper(f)){const auto&h=m.helpers->at(c.at("source_launch_key"));executed=m.prefix?std::min(m.prefix,U(h.ctas)):U(h.ctas);resident=h.resident;warps=h.warps;auto s=h.census(executed);U live=std::min(executed,U(2)*48*resident);total_nodes=s.nodes;expected_read=s.read;expected_write=s.write;limits.max_nodes_per_cta=s.max_nodes;limits.max_explicit_ranges_per_cta=std::max(U(1),s.max_ranges);limits.max_live_nodes=live*s.max_nodes;limits.max_live_explicit_ranges=std::max(U(1),live*s.max_ranges);budget={{"nodes_per_cta_max",s.max_nodes},{"stored_ranges_per_cta_max",s.max_ranges},{"control_classes",h.classes.size()},{"conservative_live_ctas",live},{"conservative_live_nodes",live*s.max_nodes},{"conservative_live_ranges",live*s.max_ranges},{"native_resource_cap",resident},{"pending_retire_replacement_frontier",true}};}else if(is_attention(f)){const J s=seals().at("frame_nodes").at(f);executed=m.prefix?std::min(m.prefix,U(8)):8;resident=int(p::natural(s.at("resident")));warps=4;U n=p::natural(s.at("nodes")),range=p::natural(s.at("ranges"));total_nodes=n*executed;expected_read=p::natural(s.at("read"))*executed;expected_write=p::natural(s.at("write"))*executed;limits.max_nodes_per_cta=n;limits.max_explicit_ranges_per_cta=range;limits.max_live_nodes=n*8;limits.max_live_explicit_ranges=range*8;budget={{"nodes_per_cta",n},{"stored_ranges_per_cta",range},{"conservative_live_ctas",executed},{"conservative_live_nodes",executed*n},{"conservative_live_ranges",executed*range},{"native_resource_cap",resident}};}
  else if(is_gemm(f)){U declared=p::natural(c.at("grid")[0]);executed=m.prefix?std::min(m.prefix,declared):declared;resident=1;warps=4;U n=p::natural(seals().at("frame_nodes").at(f).at("nodes")),range=f=="P28QKV"?374528:prefill_gemm::profile(f=="GEMMO"?"o":f=="GEMMGate"?"gate":"down").ranges;U rd=f=="P28QKV"?1310720:prefill_gemm::profile(f=="GEMMO"?"o":f=="GEMMGate"?"gate":"down").read;total_nodes=n*executed;expected_read=rd*executed;expected_write=8192*executed;limits.max_nodes_per_cta=n;limits.max_explicit_ranges_per_cta=range;limits.max_live_nodes=4190592;limits.max_live_explicit_ranges=40820736;budget={{"nodes_per_cta",n},{"stored_ranges_per_cta",range},{"conservative_live_ctas",std::min(executed,U(96))},{"conservative_live_nodes",std::min(executed,U(96))*n},{"conservative_live_ranges",std::min(executed,U(96))*range},{"native_resource_cap",1}};}
  else if(f=="GEMV"){bundle=&m.gemv->source(c);program=&bundle->program;executed=m.prefix?std::min(m.prefix,p::natural(c.at("grid")[0])):p::natural(c.at("grid")[0]);resident=bundle->resident;warps=program->warps;limits.max_live_nodes=5000000;U n=bundle->registers.nodes.size(),range=p::natural(bundle->budget.at("stored_ranges_per_cta")),front=std::min(executed,U(2)*48*resident);total_nodes=n*executed;expected_read=program->bodies[0].read*executed;expected_write=program->bodies[0].write*executed;budget={{"nodes_per_cta",n},{"stored_ranges_per_cta",range},{"conservative_live_ctas",front},{"conservative_live_nodes",front*n},{"conservative_live_ranges",front*range},{"native_resource_cap",resident}};}
  else{p::need(std::set<std::string>{"SiLU","FusedNorm","Rotary","PlainNorm","IndexPut","PrefillCopy"}.count(f),"unsupported family cannot enter legacy prepared");canonical_mixed643::ModeledPrepared old(*m.legacy,t,false);bundle=old.bundle;index_bundle=old.index_bundle;copy_bundle=old.copy_bundle;class_bundle=old.class_bundle;program=old.program;executed=m.prefix?std::min(m.prefix,old.executed):old.executed;resident=old.resident;warps=program->warps;limits=old.limits;budget=old.budget;if(class_bundle){auto&cat=class_bundle->catalog;total_nodes=cat.sum(executed,&native_cta_class::Binding::nodes);expected_read=cat.sum(executed,&native_cta_class::Binding::read);expected_write=cat.sum(executed,&native_cta_class::Binding::write);}else{total_nodes=old.total_nodes/old.executed*executed;expected_read=old.expected_read/old.executed*executed;expected_write=old.expected_write/old.executed*executed;}}
  p::need(total_nodes>0&&p::natural(budget.at("conservative_live_nodes"))<=limits.max_live_nodes&&p::natural(budget.at("conservative_live_ranges"))<=limits.max_live_explicit_ranges,"closed host graph bounds");if(eager)p::need(total_nodes<=200000,"bounded eager reference");
 }
};
}
