#pragma once
#include "sealed_inputs.h"
namespace canonical_gemv {
using namespace native_sequence;
struct Model {
 J plan;std::map<std::string,J>templates;std::vector<const J*>calls;std::unique_ptr<SourceCatalog>catalog;U prefix=0;
 Model(const J&in){
  keys(in,{"schema","plan_file","memory_model","service_address_map","selected_source_keys","prefix_ctas","max_kernel_cycles","aggregate_observations"});auto sealed=seals();p::need(in.at("schema")=="CANONICAL_GEMV_MODELED_SEQUENCE_V1"&&in.at("aggregate_observations").is_boolean(),"model envelope");prefix=p::natural(in.at("prefix_ctas"),16032);p::need(in.at("plan_file")==sealed.at("plan_file")&&in.at("memory_model")==sealed.at("memory_model"),"sealed plan/profile");plan=strict_parse(check_pin(sealed.at("plan_file")));p::need(plan.at("schema")=="CANONICAL_GEMV_STRUCTURAL_MODEL_PLAN_V1"&&plan.at("native_target_qualified")==false&&plan.at("driver_admitted")==false&&plan.at("call_count")==259&&plan.at("rejected_targets").empty(),"259 model targets including derived scratch");
  catalog=std::make_unique<SourceCatalog>(sealed.at("source_refs"),false);for(auto k:{"plan_file","model_manifest","model_source"})catalog->seals.evidence(sealed.at(k));
  for(const auto&i:sealed.at("template_files").items()){catalog->seals.evidence(i.value());p::need(plan.at("templates").at(i.key())==i.value(),"template pin");J t=strict_parse(check_pin(i.value()));const auto&s=catalog->get(i.key());p::need(t.at("register_program")==s.input.at("register_file")&&t.at("memory_program")==s.input.at("program_file"),"actual source binding");p::need(t.at("grid")==s.input.at("register_program").at("grid")&&t.at("counts").at("nodes_per_CTA")==s.registers.nodes.size()&&t.at("object_roles").size()==s.program.objects.size(),"same geometry/source census");p::need(t.at("explicit_dataflow").at("tensor_controls_observed_addresses_guards_PC")==false&&t.at("explicit_dataflow").at("relocated_pointer_controls_observed_guards_PC")==false,"explicit flow bound");templates.emplace(i.key(),std::move(t));}
  const auto&selected=in.at("selected_source_keys");p::need(selected.is_array()&&!selected.empty()&&selected.size()<=259,"selected1..259");std::set<std::string>wanted;for(const auto&k:selected)p::need(k.is_string()&&wanted.insert(k.get<std::string>()).second,"unique keys");U prior=0;J context;
  for(const auto&c:plan.at("calls"))if(wanted.count(c.at("source_launch_key").get<std::string>())){validate_call(c);p::need(selected.at(calls.size())==c.at("source_launch_key"),"native target order");U id=p::natural(c.at("native_launch_binding").at("native_launch_id"));p::need(id>prior,"increasing launches");prior=id;J cc={{"process",c.at("process")},{"context",c.at("context_id")},{"stream",c.at("stream_u64")}};if(calls.empty())context=cc;else p::need(cc==context,"one current process/context/stream");p::need(!prefix||prefix<=p::natural(c.at("grid")[0]),"prefix within target");calls.push_back(&c);}
  p::need(calls.size()==selected.size(),"unqualified/unknown target rejected");p::need(in.at("service_address_map")==service_map(),"one actual target VA union");
 }
 const SourceBundle&source(const J&c)const{return catalog->get(c.at("template_key").get<std::string>());}
 const J&tpl(const J&c)const{return templates.at(c.at("template_key").get<std::string>());}
 void validate_call(const J&c)const{
  const auto&t=tpl(c);p::need(c.at("schema")=="CANONICAL_GEMV_ESTIMATED_TARGET_V1"&&c.at("process")==J({{"pid",1925216},{"start_ticks",857625100}})&&c.at("native_launch_binding").at("process")==c.at("process")&&c.at("native_launch_binding").at("source_launch_key")==c.at("source_launch_key"),"canonical target identity");for(auto f:{"code_sha256","parameter_layout_sha256","grid","block","native_resources"})p::need(c.at(f)==t.at(f),"exact source control geometry/resource");for(auto f:{"native_target_qualified","driver_admitted","implicit_descriptor_dependencies_complete"})p::need(c.at(f)==false,"no native uplift");for(auto f:{"estimated_compute","estimated_address"})p::need(c.at(f)==true,"estimate scope");
  const auto&w=c.at("argument_words");p::need(w.is_array()&&w.size()==38,"38 argument words");std::set<int>pwords{0,1,4,5,8,9,12,13};for(int i=0;i<38;++i){p::natural(w[i],UINT32_MAX);if(!pwords.count(i))p::need(w[i]==t.at("argument_words")[i],"all120 nonpointer bytes exact");}p::need(w[8]==w[12]&&w[9]==w[13],"output pointer alias");U K=p::natural(t.at("K")),N=p::natural(t.at("N")),x=p::natural(c.at("block")[0]);p::need(N==p::multiply(p::natural(c.at("grid")[0]),p::natural(c.at("block")[1]))&&p::natural(w[35])&&K%p::multiply(x,p::natural(w[35]))==0,"complete no-tail geometry");
  int wi=0;for(auto role:{"weight","input","output"}){const auto&o=c.at("objects").at(role);U ptr=p::natural(w[wi])+(p::natural(w[wi+1])<<32);wi+=4;U extent=std::string(role)=="weight"?2*K*N:2*(std::string(role)=="input"?K:N);p::need(ptr==p::natural(o.at("pointer"))&&extent==p::natural(o.at("bytes"))&&p::add(ptr,extent)==p::natural(o.at("end_exclusive"))&&ptr%128==p::natural(t.at("pointer_alignment_mod128").at(role)),"target pointer/extent/alignment");if(o.contains("root")){p::need(p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("storage_offset_bytes")))==ptr&&p::add(ptr,extent)<=p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("root").at("storage_nbytes"))),"target typed root bounds");}else{p::need(c.at("module_scope")=="logits_processor"&&(std::string(role)=="output"||(std::string(role)=="input"&&c.at("phase")=="Prefill")),"derived scratch domain");p::need(o.at("tensor_hook_observed")==false&&o.at("allocation_lifetime_qualified")==false,"no invented hook/lifetime");std::string id="1925216:857625100:"+c.at("source_launch_key").get<std::string>()+":"+role+"_derived_scratch";p::need(o.at("logical_identity")==id,"per-call derived scratch identity");p::need(o.at("evidence_kind")== (std::string(role)=="output"?"ABI_DERIVED_VIEW_WITH_ADJACENT_CAST_POINTER_CHAIN":"ABI_DERIVED_8192_BYTE_INPUT_WITH_PRECEDING_GATHER_CORRELATION"),"exact scratch derivation");}}
 }
 U address(const J&c,const p::Lane&l,U bytes,U cta)const{
  const auto&s=source(c);const auto&roles=tpl(c).at("object_roles");std::string role=roles.at(l.object).get<std::string>();const auto&o=c.at("objects").at(role);U source_va=s.program.address(l,bytes,cta),source_base=tpl(c).contains("object_argument_bases")?p::natural(tpl(c).at("object_argument_bases").at(l.object)):s.program.objects.at(l.object).base;p::need(source_va>=source_base,"source offset");U off=source_va-source_base;p::need(p::add(off,bytes)<=p::natural(o.at("bytes")),"target affine extent");return p::add(p::natural(o.at("pointer")),off);
 }
 J service_map()const{std::vector<std::pair<U,U>>spans;for(auto*c:calls)for(auto role:{"weight","input","output"}){const auto&o=c->at("objects").at(role);U lo=p::natural(o.at("pointer")),hi=p::natural(o.at("end_exclusive"));p::need(hi<=UINT64_MAX-127,"align bound");spans.emplace_back(lo/128*128,(hi+127)/128*128);}std::sort(spans.begin(),spans.end());std::vector<std::pair<U,U>>merged;for(auto x:spans){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(merged.back().second,x.second);else merged.push_back(x);}J rows=J::array();U off=0;for(auto[lo,hi]:merged){rows.push_back({{"source_base",lo},{"bytes",hi-lo},{"service_base",off}});off=p::add(off,hi-lo);}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}
 J address_oracle(const J&c)const{tiny_sha::Sha256 h;U count=0;const auto&s=source(c);U total=prefix?prefix:p::natural(c.at("grid")[0]);for(U cta=0;cta<total;++cta){std::map<int,U>ordinal;for(const auto&r:s.program.bodies[0].records){U ord=ordinal[r.warp]++;for(const auto&l:r.lanes){h.add(std::to_string(cta)+":"+std::to_string(r.warp)+":"+std::to_string(ord)+":"+std::to_string(l.lane)+":"+std::to_string(address(c,l,r.width,cta))+"\n");++count;}}}return {{"source_launch_key",c.at("source_launch_key")},{"lane_addresses",count},{"sha256",h.hex()}};}
};
}
