#pragma once
namespace current_initial_cat {
using namespace native_sequence;
class Binding final:public tiny_full::KernelBinding {
 const J&nodes_json_;J call_;const coupling::ServiceMapper&mapper_;std::vector<tiny_full::SourceNode>nodes_;
 static std::vector<U>raw(const J&a){std::string h=a.at("raw_bytes_hex"),s;std::vector<U>v;auto nib=[](char c)->U{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;throw std::runtime_error("canonical hex");};p::need(h.size()==2*p::natural(a.at("size_bytes")),"actual raw extent");for(U i=0;i<h.size();i+=2){U x=nib(h[i])*16+nib(h[i+1]);v.push_back(x);s+=char(x);}p::need(tiny_sha::sha256(s)==a.at("sha256").get<std::string>(),"actual raw digest");return v;}
 static U word(const std::vector<U>&a,U at,U size){p::need(at+size<=a.size()&&size<=8,"actual integer field");U v=0;for(U k=0;k<size;++k)v|=a[at+k]<<(8*k);return v;}
public:
 static void admit(const J&c){const auto&b=c.at("binding");const auto&a=c.at("raw_argument_record");const auto&l=c.at("launch_before");const auto&r=c.at("launch_return");p::need(b.at("process")==J({{"pid",3011726},{"start_ticks",897090720}})&&a.at("native_launch_binding").at("process")==b.at("process")&&a.at("native_launch_binding").at("native_launch_id")==b.at("native_launch_id")&&tiny_sha::sha256(a.dump())==c.at("raw_argument_sha256").get<std::string>(),"actual current process/raw identity");for(auto k:{"code_sha256","function_id","phase"})p::need(a.at(k)==b.at(k)&&a.at(k)==l.at(k)&&a.at(k)==r.at(k),"same original paired source identity");for(auto k:{"grid","block"})p::need(l.at(k)==r.at(k)&&l.at(k)==b.at(k),"original grid and block");p::need(r.at("cuda_status")==0&&l.at("event_ordinal")<r.at("event_ordinal")&&l.at("static_shared_bytes")==0&&l.at("dynamic_shared_bytes")==0,"returned launch no omitted shared");p::need(c.at("source_DAG_exact")==false&&c.at("arithmetic_region_summary")==true&&c.at("summary_budget_is_hardware_cycle_bound")==false&&c.at("resident_limit_assumption")==1&&c.at("current_occupancy_observed")==false&&c.at("full_simulation_admitted")==false,"honest initialization-only approximation");p::need(c.at("mode")=="min"||c.at("mode")=="max","fixed arithmetic work interval");std::vector<std::vector<U>>rs;for(const auto&x:a.at("arguments"))rs.push_back(raw(x));const auto&f=b.at("fields");const auto&v=c.at("typed_output");const auto&storage=c.at("typed_storage");p::need(b.at("kind")=="cat"&&b.at("N")==1048576&&b.at("grid")==J::array({1024,2,1})&&b.at("block")==J::array({128,1,1})&&rs.size()==5,"fixed current concat kernel");p::need(word(rs[0],0,8)==f.at("output")&&word(rs[3],0,4)==1&&word(rs[4],0,4)==1&&f.at("concat_dim")==1&&f.at("dim_stride")==1,"actual concat dimension/output");for(U i=0;i<2;++i){p::need(word(rs[1],8*i,8)==f.at("inputs")[i]&&word(rs[1],1024+4*i,4)==i*64&&word(rs[1],1536+4*i,4)==64&&word(rs[1],2048+4*i,4)==524288,"actual source input metadata");p::need(c.at("source_input_producers")[i].at("native_launch_id")==8+i&&c.at("source_input_producers")[i].at("N")==524288&&c.at("source_input_producers")[i].at("output")==f.at("inputs")[i],"same-PID cos/sin producer pointer chain");}p::need(word(rs[2],0,4)==8192&&word(rs[2],4,4)==128&&word(rs[2],16,4)==128&&word(rs[2],20,4)==1,"actual row-major output ABI");p::need(v.at("shape")==J::array({8192,128})&&v.at("stride_bytes")==J::array({512,4})&&v.at("dtype")=="torch.float32"&&v.at("element_size")==4&&v.at("logical_nbytes")==4194304&&v.at("data_address")==f.at("output")&&v.at("root")==storage.at("id")&&storage.at("base_address")==f.at("output")&&storage.at("storage_nbytes")==4194304,"independent observed typed output view");
 }

 Binding(const J&t,const J&c,const coupling::ServiceMapper&map):nodes_json_(t.at(c.at("template").get<std::string>())),call_(c),mapper_(map){admit(c);for(const auto&n:nodes_json_){tiny_full::SourceNode s;s.id=p::natural(n.at("id"));s.warp=p::natural(n.at("warp"));s.ordinal=p::natural(n.at("ordinal"));s.pc=p::natural(n.at("pc"));s.source_ordinal=p::natural(n.at("source_ordinal"));s.mask=p::natural(n.at("effective_mask"));s.compute_elements=p::natural(n.at("elements"));s.pipeline=n.at("pipeline");s.write=n.at("operation")=="W";s.kind=n.at("kind")=="global"?tiny_full::Kind::Global:n.at("kind")=="control"?tiny_full::Kind::Control:tiny_full::Kind::Compute;s.completion_dependencies=n.at("completion_dependencies").get<std::vector<unsigned>>();s.issue_dependencies=n.at("issue_dependencies").get<std::vector<unsigned>>();p::need(s.id==nodes_.size(),"dense original program member");for(U x:s.completion_dependencies)p::need(x<s.id,"backward source completion dependency");for(U x:s.issue_dependencies)p::need(x<s.id,"backward source issue dependency");nodes_.push_back(std::move(s));}}
 U ctas()const override{return p::natural(call_.at("whole_grid_CTAs"));}unsigned warps(U c)const override{p::need(c<ctas(),"actual source CTA");return 4;}unsigned resident_limit()const override{return 1;}U first_node(U c)const override{p::need(c<ctas(),"original CTA span");return c*nodes_.size();}U template_class(U c)const override{p::need(c<ctas(),"actual template domain");return 0;}std::span<const tiny_full::SourceNode>nodes(U c)const override{p::need(c<ctas(),"actual node domain");return nodes_;}
 tiny_full::MemoryDescriptor memory(U c,unsigned member)const override{const auto&n=nodes_json_.at(member);p::need(n.at("kind")=="global"&&c<2048,"actual fixed-shape GLOBAL node");const auto&r=n.at("recipe");const auto&f=call_.at("binding").at("fields");const auto&v=call_.at("typed_output");tiny_full::MemoryDescriptor d;d.path=tiny_full::Path::DirectGlobal;d.write=n.at("operation")=="W";g::ExplicitMemorySubop sub;std::set<U>lines;U width=p::natural(n.at("width")),w=p::natural(n.at("warp")),by=c/1024,bx=c%1024;p::need(n.at("effective_mask")==0xffffffffu&&width==(d.write?4:16),"exact original vector-load/scalar-store masks and widths");for(U lane=0;lane<32;++lane){U flat=(bx*128+w*32+lane)*4,address=0;if(!d.write)address=p::natural(f.at("inputs")[by])+flat*4;else{U element=flat+p::natural(r.at("element"));U row=element/64,column=element%64+by*64;p::need(row<8192&&column<128,"mathematical integer division source-layout bounds");address=p::natural(v.at("data_address"))+row*p::natural(v.at("stride_bytes")[0])+column*p::natural(v.at("stride_bytes")[1]);}sub.ranges.push_back({int(lane),address,width});sub.source_member_ordinals.push_back(int(lane));sub.requested_bytes+=width;for(U line=address/128*128,last=(address+width-1)/128*128;;line+=128){(void)mapper_.map({1,line});lines.insert(line);if(line==last)break;}}d.global_bytes=sub.requested_bytes;d.global_subops.push_back(std::move(sub));for(U line:lines)d.lines.push_back({1,line});return d;}
 J evidence()const override{return {{"native_launch_id",call_.at("binding").at("native_launch_id")},{"mode",call_.at("mode")},{"source_memory_effects_preserved_under_declared_domain",true},{"compiler_integer_division_semantics_assumed",true},{"current_typed_output_layout_checked",true},{"source_dynamic_instruction_path_observed",false},{"source_DAG_exact",false},{"arithmetic_region_summary",true},{"internal_arithmetic_PC_predication_exact",false},{"exact_hardware_timing",false},{"arithmetic_budget_is_hardware_cycle_bound",false},{"conservative_per_warp_completion_chain",true},{"resident_limit_assumption",1},{"current_occupancy_observed",false},{"constant_cache_timing_modeled",false},{"full_simulation_admitted",false}};}
};
}
