#pragma once
namespace current_initial_rope {
using namespace native_sequence;
class Binding final:public tiny_full::KernelBinding {
 const J&nodes_json_;J call_;const coupling::ServiceMapper&mapper_;std::vector<tiny_full::SourceNode>nodes_;
 static std::vector<U>raw(const J&a){std::string h=a.at("raw_bytes_hex"),s;std::vector<U>v;auto nib=[](char c)->U{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;throw std::runtime_error("canonical hex");};p::need(h.size()==2*p::natural(a.at("size_bytes")),"actual raw extent");for(U i=0;i<h.size();i+=2){U x=nib(h[i])*16+nib(h[i+1]);v.push_back(x);s+=char(x);}p::need(tiny_sha::sha256(s)==a.at("sha256").get<std::string>(),"actual raw digest");return v;}
 static U word(const std::vector<U>&a,U at,U size){p::need(at+size<=a.size()&&size<=8,"actual integer field");U v=0;for(U k=0;k<size;++k)v|=a[at+k]<<(8*k);return v;}
public:
 static void admit(const J&c){const auto&b=c.at("binding");const auto&a=c.at("raw_argument_record");const auto&l=c.at("launch_before");const auto&r=c.at("launch_return");p::need(c.at("schema")=="CURRENT_INITIAL_ROPE_STRICT_EXECUTION_CALL_V1"&&b.at("process")==J({{"pid",3011726},{"start_ticks",897090720}}),"current process");p::need(a.at("native_launch_binding").at("process")==b.at("process")&&a.at("native_launch_binding").at("native_launch_id")==b.at("native_launch_id")&&tiny_sha::sha256(a.dump())==c.at("raw_argument_sha256").get<std::string>(),"actual raw launch identity");for(auto k:{"code_sha256","function_id","phase"})p::need(a.at(k)==b.at(k)&&a.at(k)==l.at(k)&&a.at(k)==r.at(k),"actual paired source identity");for(auto k:{"grid","block"})p::need(l.at(k)==r.at(k)&&l.at(k)==b.at(k),"exact original geometry");p::need(r.at("cuda_status")==0&&l.at("event_ordinal")<r.at("event_ordinal"),"actual successful return");p::need(l.at("static_shared_bytes")==0&&l.at("dynamic_shared_bytes")==0&&c.at("resident_limit_assumption")==1,"no omitted shared state, declared resident assumption");for(auto k:{"current_occupancy_observed","implicit_register_dependencies_complete","compute_transfer_qualified","full_simulation_admitted"})p::need(c.at(k)==false,"lower source qualification retained");std::vector<std::vector<U>>rs;for(const auto&arg:a.at("arguments"))rs.push_back(raw(arg));p::need(word(rs.at(0),0,4)==b.at("N"),"actual N");const auto&f=b.at("fields");
  if(b.at("kind")=="small_mul"){p::need(rs.size()==3&&rs[0].size()==4&&rs[1].size()==8&&rs[2].size()==16&&b.at("N")==64&&b.at("grid")==J::array({1,1,1})&&b.at("block")==J::array({128,1,1}),"exact small specialization");p::need(word(rs[2],0,8)==f.at("output")&&word(rs[2],8,8)==f.at("input"),"current pointer roles");std::uint32_t bits=word(rs[1],4,4);float scalar;std::memcpy(&scalar,&bits,4);p::need(double(scalar)==f.at("scalar").get<double>(),"actual scalar bytes");}
  else{p::need(b.at("kind")=="outer_mul"&&rs.size()==2&&b.at("N")==524288&&b.at("grid")==J::array({2048,1,1})&&b.at("block")==J::array({128,1,1}),"exact outer product specialization");p::need(word(rs[1],0,4)==2&&f.at("dims")==2,"actual TensorIterator rank");for(U i=0;i<2;++i)for(U j=0;j<3;++j){p::need(word(rs[1],4+i*12+j*4,4)==f.at("divisors")[i][j],"current divisor");p::need(word(rs[1],304+i*12+j*4,4)==f.at("byte_strides")[i][j],"current byte stride");}p::need(f.at("divisors")==J::array({J::array({64,1,6}),J::array({8192,1,13})})&&f.at("byte_strides")==J::array({J::array({4,0,4}),J::array({256,4,0})}),"closed source indexing domain");U i=0;for(auto role:{"output","a","b"}){p::need(word(rs[1],608+8*i++,8)==f.at(role),"actual outer role");}}
 }
 Binding(const J&t,const J&c,const coupling::ServiceMapper&map):nodes_json_(t.at(c.at("template").get<std::string>())),call_(c),mapper_(map){admit(c);for(const auto&n:nodes_json_){tiny_full::SourceNode s;s.id=p::natural(n.at("id"));s.warp=p::natural(n.at("warp"));s.ordinal=p::natural(n.at("ordinal"));s.pc=p::natural(n.at("pc"));s.source_ordinal=p::natural(n.at("source_ordinal"));s.mask=p::natural(n.at("effective_mask"));s.compute_elements=p::natural(n.at("elements"));s.pipeline=n.at("pipeline");s.write=n.at("operation")=="W";s.kind=n.at("kind")=="global"?tiny_full::Kind::Global:n.at("kind")=="control"?tiny_full::Kind::Control:tiny_full::Kind::Compute;s.completion_dependencies=n.at("completion_dependencies").get<std::vector<unsigned>>();s.issue_dependencies=n.at("issue_dependencies").get<std::vector<unsigned>>();p::need(s.id==nodes_.size(),"dense original program member");for(U x:s.completion_dependencies)p::need(x<s.id,"backward source completion dependency");for(U x:s.issue_dependencies)p::need(x<s.id,"backward source issue dependency");nodes_.push_back(std::move(s));}}
 U ctas()const override{return p::natural(call_.at("whole_grid_CTAs"));}unsigned warps(U c)const override{p::need(c<ctas(),"actual source CTA");return 4;}unsigned resident_limit()const override{return 1;}U first_node(U c)const override{p::need(c<ctas(),"original CTA span");return c*nodes_.size();}U template_class(U c)const override{p::need(c<ctas(),"actual template domain");return 0;}std::span<const tiny_full::SourceNode>nodes(U c)const override{p::need(c<ctas(),"actual node domain");return nodes_;}
 tiny_full::MemoryDescriptor memory(U c,unsigned member)const override{const auto&n=nodes_json_.at(member);p::need(n.at("kind")=="global","actual original GLOBAL node");const auto&r=n.at("recipe");tiny_full::MemoryDescriptor d;d.path=tiny_full::Path::DirectGlobal;d.write=n.at("operation")=="W";g::ExplicitMemorySubop sub;std::set<U>lines;U mask=p::natural(n.at("effective_mask")),width=p::natural(n.at("width")),w=p::natural(n.at("warp")),base=p::natural(call_.at("binding").at("fields").at(r.at("role").get<std::string>()));p::need(width==4&&mask,"supported exact FP32 memory effect");
  for(U lane=0;lane<32;++lane)if(mask>>lane&1){U offset=0;if(call_.at("binding").at("kind")=="small_mul")offset=w*128+lane*4;else{U index=c*256+w*32+lane+p::natural(r.at("addend"));p::need(index<524288,"whole current source element range");offset=(r.at("form")=="row"?index/64:r.at("form")=="col"?index%64:index)*4;}U address=p::add(base,offset);sub.ranges.push_back({int(lane),address,width});sub.source_member_ordinals.push_back(int(lane));sub.requested_bytes+=width;for(U line=address/128*128,last=(address+width-1)/128*128;;line+=128){(void)mapper_.map({1,line});lines.insert(line);if(line==last)break;}}
  d.global_bytes=sub.requested_bytes;d.global_subops.push_back(std::move(sub));for(U line:lines)d.lines.push_back({1,line});return d;}
 J evidence()const override{return {{"native_launch_id",call_.at("binding").at("native_launch_id")},{"source_control_derived",true},{"source_dynamic_instruction_path_observed",false},{"original_PC_and_explicit_register_DAG_preserved",true},{"GLOBAL_program_not_used_as_execution_DAG",true},{"resident_limit_assumption",1},{"current_occupancy_observed",false},{"constant_cache_timing_modeled",false},{"implicit_register_dependencies_complete",false},{"compute_transfer_qualified",false},{"full_simulation_admitted",false}};}
};
}
