#pragma once
#include "sealed_inputs.h"
namespace canonical_rotary {
using namespace native_cta_sequence;
using native_sequence::check_pin;
struct Model{
 J plan,templ;std::vector<const J*>calls;std::unique_ptr<SourceCatalog>catalog;
 Model(const J&in){keys(in,{"schema","plan_file","memory_model","service_address_map","selected_source_keys","max_kernel_cycles","aggregate_observations"});p::need(in.at("schema")=="CANONICAL_ROTARY_MODELED_SEQUENCE_V1"&&in.at("aggregate_observations").is_boolean(),"Rotary model input");auto s=seals();p::need(in.at("plan_file")==s.at("plan_file")&&in.at("memory_model")==s.at("memory_model"),"sealed input/model");plan=strict_parse(check_pin(s.at("plan_file")));templ=strict_parse(check_pin(s.at("template_file")));
  p::need(plan.at("schema")=="CANONICAL_ROTARY_STRUCTURAL_MODEL_PLAN_V1"&&plan.at("driver_admitted")==false&&plan.at("native_target_qualified")==false&&plan.at("full_workflow_qualified")==false,"model-only boundary");p::need(plan.at("template")==s.at("template_file"),"frozen template");catalog=std::make_unique<SourceCatalog>(s.at("source_catalog"),false);for(auto key:{"plan_file","template_file","model_manifest","model_source"})catalog->seals.evidence(s.at(key));
  const auto& chosen=in.at("selected_source_keys");p::need(chosen.is_array()&&chosen.size()>0&&chosen.size()<=96,"bounded chosen list");std::set<std::string>wanted;for(const auto&k:chosen)p::need(k.is_string()&&wanted.insert(k.get<std::string>()).second,"unique selected keys");U prior=0;J context;
  for(const auto&c:plan.at("calls"))if(wanted.count(c.at("source_launch_key").get<std::string>())){validate_call(c);p::need(chosen.at(calls.size())==c.at("source_launch_key"),"actual target order");U id=p::natural(c.at("native_launch_binding").at("native_launch_id"));p::need(id>prior,"increasing actual launch");prior=id;J now={{"process",c.at("process")},{"context_id",c.at("context_id")},{"stream_u64",c.at("stream_u64")}};if(calls.empty())context=now;else p::need(context==now,"same PID/context/stream");calls.push_back(&c);}
  p::need(calls.size()==chosen.size()&&in.at("service_address_map")==service_map(),"chosen complete/current VA map");
 }
 const SourceBundle&source(const J&c)const{return catalog->get(c.at("phase").get<std::string>());}
 void validate_call(const J&c)const{
  p::need(c.at("schema")=="CANONICAL_ROTARY_ESTIMATED_TARGET_V1"&&c.at("process")==plan.at("source_process")&&c.at("native_launch_binding").at("process")==c.at("process")&&c.at("native_launch_binding").at("source_launch_key")==c.at("source_launch_key"),"current source binding");
  const auto&s=source(c);p::need(c.at("code_sha256")==s.program.identity.at("begin").at("code_sha256")&&c.at("grid")==s.program.identity.at("begin").at("grid")&&c.at("block")==J::array({16,8,1}),"closed target code/geometry");
  for(auto k:{"estimated_compute","estimated_address"})p::need(c.at(k)==true,"estimate flags");for(auto k:{"native_target_qualified","driver_admitted","implicit_descriptor_dependencies_complete"})p::need(c.at(k)==false,"no hardware promotion");p::need(c.at("implicit_descriptor_base").is_null()&&c.at("implicit_descriptor_width").is_null(),"unknown descriptor remains null");
  const auto&a=c.at("arguments");U nnz=c.at("phase")=="Prefill"?32:1;p::need(p::natural(a.at("nnz"))==nnz&&p::natural(a.at("num_qo_heads"))==32&&p::natural(a.at("num_kv_heads"))==8&&p::natural(a.at("rotary_dim"))==128,"fixed structural arguments");p::need(c.at("positions").size()==nnz,"current positions length");for(const auto&v:c.at("positions"))p::need(p::natural(v,8191)<8192,"current bounded positions");
  for(auto key:{"q","k","q_rope","k_rope"}){auto role=std::string(key);U expected=nnz==32?6144:(role[0]=='q'?4096:1024);p::need(p::natural(a.at(role+"_stride_n"))==expected&&p::natural(a.at(role+"_stride_h"))==128,"stride domain");}p::need(a.at("q")==a.at("q_rope")&&a.at("k")==a.at("k_rope"),"fixed in-place form");
  const auto&r=c.at("native_resources");p::need(r.at("max_active_blocks_per_sm")==12&&r.at("threads_per_cta")==128&&r.at("static_shared_bytes")==0&&r.at("dynamic_shared_bytes")==0&&r.at("occupancy_query_result")==0,"actual target capacity");
  for(auto role:{"q","k","q_rope","k_rope","cos_sin_cache","pos_ids"}){const auto&o=c.at("objects").at(role);U base=p::natural(a.at(role)),extent=p::natural(o.at("span_bytes"));p::need(base&&base%(std::string(role)=="pos_ids"?8:16)==0&&base==p::natural(o.at("pointer"))&&p::add(base,extent)==p::natural(o.at("end_exclusive")),"actual typed pointer extent");p::need(p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("storage_offset_bytes")))==base&&p::add(base,extent)<=p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("root").at("storage_nbytes"))),"current logical root bounds");}
 }
 U address(const J&c,U cta,U warp,U lane,U pc,U width)const{
  const auto&a=c.at("arguments");U gx=p::natural(c.at("grid")[0]),bx=cta%gx,by=cta/gx,tx=(32*warp+lane)%16,ty=(32*warp+lane)/16,idx=bx*8+ty;p::need(cta<gx*40&&warp<4&&lane<32&&idx<p::natural(a.at("nnz")),"live lane domain");std::string role;U offset=0;
  if(pc==0x120){role="pos_ids";offset=8*idx;}
  else if(pc==0x310||pc==0x320||pc==0x330||pc==0x340){role="cos_sin_cache";U pos=p::natural(c.at("positions")[idx],8191);offset=4*(pos*128+(tx*8)%64+((pc==0x330||pc==0x340)?64:0))+((pc==0x320||pc==0x340)?16:0);}
  else{p::need(pc==0x400||pc==0x5a0||pc==0x810||pc==0x8c0||pc==0xa60||pc==0xcd0,"closed tensor PC");role=by<32?"q":"k";U head=by<32?by:by-32,element=tx*8;if(pc==0x5a0||pc==0xa60)element=tx<8?element+64:element-64;if(pc==0x810||pc==0xcd0)role+="_rope";offset=2*(idx*p::natural(a.at(role+"_stride_n"))+head*p::natural(a.at(role+"_stride_h"))+element);}
  const auto&o=c.at("objects").at(role);U va=p::add(p::natural(a.at(role)),offset);p::need(va>=p::natural(o.at("pointer"))&&p::add(va,width)<=p::natural(o.at("end_exclusive"))&&va%width==0,"full target instruction address");return va;
 }
 J service_map()const{
  std::vector<std::pair<U,U>>spans;for(auto*c:calls)for(const auto&o:c->at("objects")){U lo=p::natural(o.at("pointer")),hi=p::natural(o.at("end_exclusive"));p::need(hi<=UINT64_MAX-127,"map overflow");spans.emplace_back(lo/128*128,(hi+127)/128*128);}std::sort(spans.begin(),spans.end());std::vector<std::pair<U,U>>merged;for(auto x:spans){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(x.second,merged.back().second);else merged.push_back(x);}J rows=J::array();U offset=0;for(auto[lo,hi]:merged){rows.push_back({{"source_base",lo},{"bytes",hi-lo},{"service_base",offset}});offset=p::add(offset,hi-lo);}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};
 }
 J address_oracle(const J&c)const{const auto&s=source(c);tiny_sha::Sha256 h;U count=0;for(U cta=0;cta<s.program.ctas;++cta){const auto&reg=s.catalog.program(cta);const auto&body=s.program.body(cta);for(const auto&wn:reg.warp_nodes)for(int flat:wn){const auto&n=reg.nodes[flat];if(n.kind!="global")continue;const auto&mem=body.records[s.catalog.record(cta,n)];for(const auto&lane:mem.lanes){h.add(std::to_string(cta)+":"+std::to_string(n.warp)+":"+std::to_string(n.memory)+":"+std::to_string(lane.lane)+":"+std::to_string(address(c,cta,n.warp,lane.lane,mem.pc,mem.width))+"\n");++count;}}}return {{"source_launch_key",c.at("source_launch_key")},{"lane_addresses",count},{"sha256",h.hex()}};}
};
}
