#pragma once
#include "sealed_inputs.h"
namespace canonical_norm {
using namespace native_sequence;
struct Formula{U warp,ordinal,pc,width;char op;std::string role,opcode;};
struct Model{
 J plan;std::map<std::string,J> templates;std::map<std::string,std::vector<Formula>> records;std::vector<const J*>calls;std::unique_ptr<SourceCatalog>catalog;
 Model(const J& in){
  keys(in,{"schema","plan_file","memory_model","service_address_map","selected_source_keys","max_kernel_cycles","aggregate_observations"});const auto sealed=seals();p::need(in.at("schema")=="CANONICAL_NORM_MODELED_SEQUENCE_V1"&&in.at("aggregate_observations").is_boolean(),"explicit model envelope");p::need(in.at("plan_file")==sealed.at("plan_file")&&in.at("memory_model")==sealed.at("memory_model"),"sealed plan and frozen model parameters");
  plan=strict_parse(check_pin(sealed.at("plan_file")));p::need(plan.at("schema")=="CANONICAL_NORM_STRUCTURAL_MODEL_PLAN_V1"&&plan.at("driver_admitted")==false&&plan.at("native_target_qualified")==false&&plan.at("full_workflow_qualified")==false,"model-only plan boundary");p::need(plan.at("calls").size()==3&&plan.at("source_process")==J({{"pid",1925216},{"start_ticks",857625100}}),"canonical3 process");
  catalog=std::make_unique<SourceCatalog>(sealed.at("source_refs"),false);for(auto key:{"plan_file","model_manifest","model_source"})catalog->seals.evidence(sealed.at(key));
  for(const auto& item:sealed.at("template_files").items()){
   const auto& phase=item.key();const auto&q=item.value();p::need(plan.at("templates").at(phase)==q,"plan template seal");catalog->seals.evidence(q);auto t=strict_parse(check_pin(q));const auto&s=catalog->get(phase);p::need(t.at("register_program")==s.input.at("register_file")&&t.at("memory_program")==s.input.at("program_file"),"actual source template binding");
   p::need(s.program.warps==16&&s.registers.nodes.size()==2991&&s.registers.global_nodes==64&&s.registers.shared_nodes==34&&s.registers.barrier_nodes==32&&s.resident==3,"Norm exact source census");
   std::map<std::pair<U,U>,Formula> fs;
   for(const auto&r:t.at("memory_records")){Formula v{p::natural(r.at("warp"),15),p::natural(r.at("ordinal"),3),p::natural(r.at("pc")),p::natural(r.at("width"),16),r.at("op").get<std::string>().at(0),r.at("role").get<std::string>(),r.at("opcode").get<std::string>()};bool good=(v.pc==0xb40&&v.op=='R'&&v.role=="input")||(v.pc==0x1a20&&v.op=='R'&&v.role=="input")||(v.pc==0x1a60&&v.op=='R'&&v.role=="weight")||(v.pc==0x1d80&&v.op=='W'&&v.role=="output");p::need(good&&v.width==16&&fs.emplace(std::make_pair(v.warp,v.ordinal),v).second,"closed formula and unique ordinal");}
   std::array<U,16> ord{};auto& vector=records[phase];for(const auto&r:s.program.bodies[0].records){auto it=fs.find({U(r.warp),ord[r.warp]++});p::need(it!=fs.end(),"missing perwarp ordinal");const auto&v=it->second;p::need(v.pc==r.pc&&v.width==U(r.width)&&v.op==r.op&&v.opcode==s.program.opcodes[r.opcode]&&r.mask==UINT32_MAX&&r.lanes.size()==32,"exact native record-to-neutral formula");for(int lane=0;lane<32;++lane)p::need(r.lanes[lane].lane==lane,"ordered source lanes");vector.push_back(v);}p::need(vector.size()==fs.size()&&vector.size()==64,"complete64records");templates.emplace(phase,std::move(t));
  }
  const auto& selected=in.at("selected_source_keys");p::need(selected.is_array()&&!selected.empty()&&selected.size()<=3,"one through3 explicit target calls");std::set<std::string>wanted;for(const auto&k:selected)p::need(k.is_string()&&wanted.insert(k.get<std::string>()).second,"unique selected key");U prior=0,ctas=0;J context;
  for(const auto&c:plan.at("calls"))if(wanted.count(c.at("source_launch_key").get<std::string>())){validate_call(c);p::need(selected.at(calls.size())==c.at("source_launch_key"),"actual original source order");U id=p::natural(c.at("native_launch_binding").at("native_launch_id"));p::need(id>prior,"increasing launch order");prior=id;J current={{"process",c.at("process")},{"context_id",c.at("context_id")},{"stream_u64",c.at("stream_u64")}};if(calls.empty())context=current;else p::need(context==current,"same canonical process/context/stream");calls.push_back(&c);ctas+=p::natural(c.at("grid")[0]);}
  p::need(calls.size()==selected.size()&&ctas<=34,"complete selected target set");p::need(in.at("service_address_map")==service_map(),"target actual VA union required");
 }
 const SourceBundle& source(const J& c)const{return catalog->get(c.at("phase")=="Prefill"?"Prefill":"Decode1");}
 const std::vector<Formula>& records_for(const J&c)const{return records.at(c.at("phase")=="Prefill"?"Prefill":"Decode1");}
 void validate_call(const J&c)const{
  p::need(c.at("schema")=="CANONICAL_NORM_ESTIMATED_TARGET_V1"&&c.at("process")==plan.at("source_process")&&c.at("native_launch_binding").at("process")==c.at("process")&&c.at("native_launch_binding").at("source_launch_key")==c.at("source_launch_key"),"canonical current argument identity");
  const auto&s=source(c);p::need(c.at("code_sha256")==s.input.at("register_program").at("code_sha256"),"target code");for(auto k:{"estimated_compute","estimated_address"})p::need(c.at(k)==true,"structural estimate flag");for(auto k:{"native_target_qualified","driver_admitted","implicit_descriptor_dependencies_complete"})p::need(c.at(k)==false,"no qualification uplift");p::need(c.at("implicit_descriptor_base").is_null()&&c.at("implicit_descriptor_width").is_null(),"unknown UR preserved");
  U rows=c.at("phase")=="Prefill"?32:1;p::need(c.at("grid")==J::array({rows,1,1})&&c.at("block")==J::array({32,16,1}),"target geometry");const auto&a=c.at("arguments");for(auto k:{"hidden_size","input_stride_elements","output_stride_elements"})p::need(p::natural(a.at(k))==4096,"scalar structure");p::need(p::natural(a.at("weight_bias_bits"))==0&&p::natural(a.at("eps_bits"))==0x3727c5ac,"same scalar bits");const auto&r=c.at("native_resources");p::need(r.at("max_active_blocks_per_sm")==3&&r.at("threads_per_cta")==512&&r.at("registers")==37&&r.at("dynamic_shared_bytes")==64&&r.at("static_shared_bytes")==0&&r.at("occupancy_query_result")==0,"actual native resource bound");
  for(auto role:{"input","output","weight"}){const auto&o=c.at("objects").at(role);U base=p::natural(a.at(role)),extent=8192*(std::string(role)=="weight"?1:rows);p::need(base&&base%16==0&&base==p::natural(o.at("pointer"))&&extent==p::natural(o.at("bytes"))&&p::add(base,extent)==p::natural(o.at("end_exclusive")),"pointer full extent");p::need(p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("storage_offset_bytes")))==base&&p::add(base,extent)<=p::add(p::natural(o.at("root").at("base_address")),p::natural(o.at("root").at("storage_nbytes"))),"current object root");std::string id=std::to_string(p::natural(c.at("process").at("pid")))+":"+std::to_string(p::natural(c.at("process").at("start_ticks")))+":"+o.at("root").at("id").get<std::string>();p::need(o.at("logical_identity")==id,"logical object identity");}
 }
 U address(const J&c,U cta,const Formula&r,U lane)const{
  p::need(cta<p::natural(c.at("grid")[0])&&lane<32&&r.warp<16&&r.width==16,"formula coordinate domain");U stride=r.role=="weight"?0:p::natural(c.at("arguments").at(r.role+"_stride_elements"));U offset=p::multiply(2,p::add(p::multiply(cta,stride),8*(32*r.warp+lane)));U a=p::add(p::natural(c.at("arguments").at(r.role)),offset);const auto&o=c.at("objects").at(r.role);p::need(a>=p::natural(o.at("pointer"))&&p::add(a,16)<=p::natural(o.at("end_exclusive")),"generated current call extent");return a;
 }
 J service_map()const{std::vector<std::pair<U,U>>spans;for(auto*c:calls)for(auto role:{"input","output","weight"}){const auto&o=c->at("objects").at(role);U lo=p::natural(o.at("pointer")),hi=p::natural(o.at("end_exclusive"));p::need(hi<=UINT64_MAX-127,"aligned map bound");spans.emplace_back(lo/128*128,(hi+127)/128*128);}std::sort(spans.begin(),spans.end());std::vector<std::pair<U,U>>merged;for(auto x:spans){if(!merged.empty()&&x.first<=merged.back().second)merged.back().second=std::max(x.second,merged.back().second);else merged.push_back(x);}J rows=J::array();U off=0;for(auto[lo,hi]:merged){rows.push_back({{"source_base",lo},{"bytes",hi-lo},{"service_base",off}});off=p::add(off,hi-lo);}return {{"schema","SG_SOURCE_TO_SERVICE_MAP_V1"},{"qualification","PACKED_SOURCE_GENERATED_128B_LINES_NOT_PHYSICAL_HARDWARE_ADDRESSES"},{"spans",rows}};}
 J address_oracle(const J&c)const{tiny_sha::Sha256 h;U count=0;for(U cta=0;cta<p::natural(c.at("grid")[0]);++cta)for(const auto&r:records_for(c))for(U l=0;l<32;++l){h.add(std::to_string(cta)+":"+std::to_string(r.warp)+":"+std::to_string(r.ordinal)+":"+std::to_string(l)+":"+std::to_string(address(c,cta,r,l))+"\n");++count;}return {{"source_launch_key",c.at("source_launch_key")},{"lane_addresses",count},{"sha256",h.hex()}};}
};
}
